### ISSUE TITLE
[Question] Any Plans to Develop This Project?

### ISSUE THREAD

**Issue by ebebbington** [justjavac/deno_ssh#1]
Hey, I was planning on making an ssh client module myself, but thought it would be pointless when i saw this project as someone would already be developing one.

But the project seems to have not started yet - do you plan on developing this module?

**Comment by justjavac** [comment]
I just finished the development of [deno_num_cpus](https://github.com/justjavac/deno_num_cpus) this weekend, next week I will develop libssh2 bingding for Deno.

Do you have any good ideas?

**Comment by ebebbington** [comment]
Oh cool, ok :) No good ideas atm unfortunately, I was just trying to follow NPM's `ssh2` loosely, eg `const client =. new SSHClient(...); await client.exec("ls")`, and looks like you'll do a much better job - will close this 'issue'!
