### ISSUE TITLE
Did you ever find an alternative?

### ISSUE THREAD

**Issue by johnstonmatt** [justjavac/deno_ssh#2]
I'm interested in a project like this and I'm curious if you found any elegant solutions for this type of thing in the ecosystem?

**Comment by justjavac** [comment]
I created a libssh2 raw binding https://github.com/denoffi/deno_libssh2, but I ran into a problem: the [`libssh2_session_handshake`](https://www.libssh2.org/libssh2_session_handshake.html) function expects a socket as a parameter.

```c
int libssh2_session_handshake(LIBSSH2_SESSION *session, libssh2_socket_t socket);
//                                                      ^^^^^^^^^^^^^^^^^^^^^^^
//                                                      HEAR
```

**Comment by justjavac** [comment]
maybe web can use libsocket https://github.com/dermesser/libsocket

**Comment by johnstonmatt** [comment]
I was thinking i might try the FFI approach with the Rust SSH2 crate next week, does that have potential to solve the issue?

This is the first time I've ever needed to write native code, but with Deno itself being rust i thought it was a natural fit

[https://docs.rs/ssh2/latest/ssh2/index.html](https://docs.rs/ssh2/latest/ssh2/index.html)

**Comment by johnstonmatt** [comment]
the library is now supported natively in Deno
